# Generated by Django 5.2.4 on 2025-08-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(blank=True, help_text='e.g., smtp.gmail.com', max_length=100, null=True)),
                ('email_port', models.PositiveIntegerField(default=587, help_text='e.g., 587 for TLS')),
                ('email_host_user', models.EmailField(blank=True, help_text="The 'from' email address", max_length=254, null=True)),
                ('email_host_password', models.CharField(blank=True, help_text="Use an 'App Password' for services like Gmail", max_length=100, null=True)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('default_from_email', models.EmailField(blank=True, help_text='e.g., Aronee <noreply@gminitours.com>', max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
