# Generated by Django 5.2.4 on 2025-08-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('coming_from', models.CharField(blank=True, max_length=200, null=True)),
                ('from_location', models.CharField(blank=True, max_length=200, null=True)),
                ('to_location', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_type_selected', models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Van', 'Van'), ('Minibus', 'Minibus')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
