# Generated by Django 5.2.4 on 2025-08-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(default='Honda', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='Jazz', max_length=50),
            preserve_default=False,
        ),
    ]
