# Generated by Django 5.2.4 on 2025-08-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_make_vehicle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Default price per extra kilometer for non-package trips.', max_digits=10),
        ),
    ]
