# Generated by Django 5.2.4 on 2025-08-03 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Van', 'Van'), ('Minibus', 'Minibus')], max_length=10)),
                ('vehicle_model', models.CharField(help_text='e.g., Innova, Swift Dzire', max_length=100)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_charge_per_km', models.DecimalField(decimal_places=2, help_text='Cost for each extra kilometer', max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='package_type',
        ),
        migrations.AddField(
            model_name='trip',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.package'),
        ),
    ]
