# Generated by Django 5.2.4 on 2025-08-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_package_remove_trip_package_type_trip_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='final_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='final_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
