# Generated by Django 5.2.4 on 2025-08-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_final_payment_amount_trip_final_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='vendor_advance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Advance paid to the vendor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='vendor_advance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='vendor_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be paid to the vendor', max_digits=10, null=True),
        ),
    ]
